[package]
name = "balance"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.1.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.34"
solana-sdk = "2.1.7"
futures = "0.3"
