geyser_url: "your_geyser_url"  # Replace with your geyser URL
wallet_private_key: "your_private_key"  # Replace with your wallet private key
recipient_address: "recipient_address"  # Replace with recipient's address