wallet_private_key: "your_private_key"  # Replace with your wallet private key
recipient_address: "your_recipient_address"  # Replace with recipient's address
geyser_url: "https://grpc.ny.shyft.to "
token: "881e801b-7dc1-4b3e-b5c7-bccd41552961"
pool_address: "your_recipient_address"