[package]
name = "transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.1.7"
solana-sdk = "2.1.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
clap = { version = "4.5.23", features = ["derive"] }
